// Code generated by Fern. DO NOT EDIT.

package client

import (
	os "os"

	accountupdaterclient "github.com/Basis-Theory/go-sdk/v6/accountupdater/client"
	agenticclient "github.com/Basis-Theory/go-sdk/v6/agentic/client"
	client "github.com/Basis-Theory/go-sdk/v6/applepay/client"
	applicationkeys "github.com/Basis-Theory/go-sdk/v6/applicationkeys"
	applications "github.com/Basis-Theory/go-sdk/v6/applications"
	applicationtemplates "github.com/Basis-Theory/go-sdk/v6/applicationtemplates"
	core "github.com/Basis-Theory/go-sdk/v6/core"
	documentsclient "github.com/Basis-Theory/go-sdk/v6/documents/client"
	enrichments "github.com/Basis-Theory/go-sdk/v6/enrichments"
	googlepayclient "github.com/Basis-Theory/go-sdk/v6/googlepay/client"
	internal "github.com/Basis-Theory/go-sdk/v6/internal"
	keys "github.com/Basis-Theory/go-sdk/v6/keys"
	logs "github.com/Basis-Theory/go-sdk/v6/logs"
	networktokensclient "github.com/Basis-Theory/go-sdk/v6/networktokens/client"
	option "github.com/Basis-Theory/go-sdk/v6/option"
	permissions "github.com/Basis-Theory/go-sdk/v6/permissions"
	proxies "github.com/Basis-Theory/go-sdk/v6/proxies"
	reactorsclient "github.com/Basis-Theory/go-sdk/v6/reactors/client"
	roles "github.com/Basis-Theory/go-sdk/v6/roles"
	sessions "github.com/Basis-Theory/go-sdk/v6/sessions"
	tenantsclient "github.com/Basis-Theory/go-sdk/v6/tenants/client"
	threedsclient "github.com/Basis-Theory/go-sdk/v6/threeds/client"
	tokenintents "github.com/Basis-Theory/go-sdk/v6/tokenintents"
	tokens "github.com/Basis-Theory/go-sdk/v6/tokens"
	webhooksclient "github.com/Basis-Theory/go-sdk/v6/webhooks/client"
)

type Client struct {
	Applications         *applications.Client
	ApplicationKeys      *applicationkeys.Client
	ApplicationTemplates *applicationtemplates.Client
	ApplePay             *client.Client
	GooglePay            *googlepayclient.Client
	Documents            *documentsclient.Client
	Tokens               *tokens.Client
	Enrichments          *enrichments.Client
	Keys                 *keys.Client
	Logs                 *logs.Client
	NetworkTokens        *networktokensclient.Client
	Permissions          *permissions.Client
	Proxies              *proxies.Client
	Reactors             *reactorsclient.Client
	Roles                *roles.Client
	Sessions             *sessions.Client
	TokenIntents         *tokenintents.Client
	Webhooks             *webhooksclient.Client
	AccountUpdater       *accountupdaterclient.Client
	Agentic              *agenticclient.Client
	Tenants              *tenantsclient.Client
	Threeds              *threedsclient.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		Applications:         applications.NewClient(options),
		ApplicationKeys:      applicationkeys.NewClient(options),
		ApplicationTemplates: applicationtemplates.NewClient(options),
		ApplePay:             client.NewClient(options),
		GooglePay:            googlepayclient.NewClient(options),
		Documents:            documentsclient.NewClient(options),
		Tokens:               tokens.NewClient(options),
		Enrichments:          enrichments.NewClient(options),
		Keys:                 keys.NewClient(options),
		Logs:                 logs.NewClient(options),
		NetworkTokens:        networktokensclient.NewClient(options),
		Permissions:          permissions.NewClient(options),
		Proxies:              proxies.NewClient(options),
		Reactors:             reactorsclient.NewClient(options),
		Roles:                roles.NewClient(options),
		Sessions:             sessions.NewClient(options),
		TokenIntents:         tokenintents.NewClient(options),
		Webhooks:             webhooksclient.NewClient(options),
		AccountUpdater:       accountupdaterclient.NewClient(options),
		Agentic:              agenticclient.NewClient(options),
		Tenants:              tenantsclient.NewClient(options),
		Threeds:              threedsclient.NewClient(options),
		options:              options,
		baseURL:              options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
