// This file was auto-generated by Fern from our API Definition.

package client

import (
	applepayclient "github.com/Basis-Theory/go-sdk/applepay/client"
	applicationkeys "github.com/Basis-Theory/go-sdk/applicationkeys"
	applications "github.com/Basis-Theory/go-sdk/applications"
	applicationtemplates "github.com/Basis-Theory/go-sdk/applicationtemplates"
	core "github.com/Basis-Theory/go-sdk/core"
	enrichments "github.com/Basis-Theory/go-sdk/enrichments"
	googlepay "github.com/Basis-Theory/go-sdk/googlepay"
	internal "github.com/Basis-Theory/go-sdk/internal"
	logs "github.com/Basis-Theory/go-sdk/logs"
	option "github.com/Basis-Theory/go-sdk/option"
	permissions "github.com/Basis-Theory/go-sdk/permissions"
	proxies "github.com/Basis-Theory/go-sdk/proxies"
	reactorsclient "github.com/Basis-Theory/go-sdk/reactors/client"
	roles "github.com/Basis-Theory/go-sdk/roles"
	sessions "github.com/Basis-Theory/go-sdk/sessions"
	tenantsclient "github.com/Basis-Theory/go-sdk/tenants/client"
	threedsclient "github.com/Basis-Theory/go-sdk/threeds/client"
	tokenintents "github.com/Basis-Theory/go-sdk/tokenintents"
	tokens "github.com/Basis-Theory/go-sdk/tokens"
	webhooksclient "github.com/Basis-Theory/go-sdk/webhooks/client"
	http "net/http"
	os "os"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	ApplePay             *applepayclient.Client
	Applications         *applications.Client
	ApplicationKeys      *applicationkeys.Client
	ApplicationTemplates *applicationtemplates.Client
	Tokens               *tokens.Client
	Enrichments          *enrichments.Client
	Googlepay            *googlepay.Client
	Logs                 *logs.Client
	Permissions          *permissions.Client
	Proxies              *proxies.Client
	Reactors             *reactorsclient.Client
	Roles                *roles.Client
	Sessions             *sessions.Client
	TokenIntents         *tokenintents.Client
	Webhooks             *webhooksclient.Client
	Tenants              *tenantsclient.Client
	Threeds              *threedsclient.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:               options.ToHeader(),
		ApplePay:             applepayclient.NewClient(opts...),
		Applications:         applications.NewClient(opts...),
		ApplicationKeys:      applicationkeys.NewClient(opts...),
		ApplicationTemplates: applicationtemplates.NewClient(opts...),
		Tokens:               tokens.NewClient(opts...),
		Enrichments:          enrichments.NewClient(opts...),
		Googlepay:            googlepay.NewClient(opts...),
		Logs:                 logs.NewClient(opts...),
		Permissions:          permissions.NewClient(opts...),
		Proxies:              proxies.NewClient(opts...),
		Reactors:             reactorsclient.NewClient(opts...),
		Roles:                roles.NewClient(opts...),
		Sessions:             sessions.NewClient(opts...),
		TokenIntents:         tokenintents.NewClient(opts...),
		Webhooks:             webhooksclient.NewClient(opts...),
		Tenants:              tenantsclient.NewClient(opts...),
		Threeds:              threedsclient.NewClient(opts...),
	}
}
