// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	v4 "github.com/Basis-Theory/go-sdk/v4"
	domain "github.com/Basis-Theory/go-sdk/v4/applepay/domain"
	client "github.com/Basis-Theory/go-sdk/v4/applepay/merchant/client"
	session "github.com/Basis-Theory/go-sdk/v4/applepay/session"
	core "github.com/Basis-Theory/go-sdk/v4/core"
	internal "github.com/Basis-Theory/go-sdk/v4/internal"
	option "github.com/Basis-Theory/go-sdk/v4/option"
	http "net/http"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient
	Merchant        *client.Client
	Domain          *domain.Client
	Session         *session.Client

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		Merchant:        client.NewClient(opts...),
		Domain:          domain.NewClient(opts...),
		Session:         session.NewClient(opts...),
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

func (c *Client) Create(
	ctx context.Context,
	request *v4.ApplePayCreateRequest,
	opts ...option.RequestOption,
) (*v4.ApplePayCreateResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*v4.ApplePayToken, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}
