// Code generated by Fern. DO NOT EDIT.

package merchant

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersApplePayMerchantCertificatesRegisterRequest(t *testing.T) {
	t.Run("SetMerchantCertificateData", func(t *testing.T) {
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValueMerchantCertificateData *string
		obj.SetMerchantCertificateData(fernTestValueMerchantCertificateData)
		assert.Equal(t, fernTestValueMerchantCertificateData, obj.MerchantCertificateData)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMerchantCertificatePassword", func(t *testing.T) {
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValueMerchantCertificatePassword *string
		obj.SetMerchantCertificatePassword(fernTestValueMerchantCertificatePassword)
		assert.Equal(t, fernTestValueMerchantCertificatePassword, obj.MerchantCertificatePassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPaymentProcessorCertificateData", func(t *testing.T) {
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValuePaymentProcessorCertificateData string
		obj.SetPaymentProcessorCertificateData(fernTestValuePaymentProcessorCertificateData)
		assert.Equal(t, fernTestValuePaymentProcessorCertificateData, obj.PaymentProcessorCertificateData)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPaymentProcessorCertificatePassword", func(t *testing.T) {
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValuePaymentProcessorCertificatePassword string
		obj.SetPaymentProcessorCertificatePassword(fernTestValuePaymentProcessorCertificatePassword)
		assert.Equal(t, fernTestValuePaymentProcessorCertificatePassword, obj.PaymentProcessorCertificatePassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomain", func(t *testing.T) {
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValueDomain *string
		obj.SetDomain(fernTestValueDomain)
		assert.Equal(t, fernTestValueDomain, obj.Domain)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitApplePayMerchantCertificatesRegisterRequest(t *testing.T) {
	t.Run("SetMerchantCertificateData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValueMerchantCertificateData *string

		// Act
		obj.SetMerchantCertificateData(fernTestValueMerchantCertificateData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMerchantCertificatePassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValueMerchantCertificatePassword *string

		// Act
		obj.SetMerchantCertificatePassword(fernTestValueMerchantCertificatePassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPaymentProcessorCertificateData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValuePaymentProcessorCertificateData string

		// Act
		obj.SetPaymentProcessorCertificateData(fernTestValuePaymentProcessorCertificateData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPaymentProcessorCertificatePassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValuePaymentProcessorCertificatePassword string

		// Act
		obj.SetPaymentProcessorCertificatePassword(fernTestValuePaymentProcessorCertificatePassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ApplePayMerchantCertificatesRegisterRequest{}
		var fernTestValueDomain *string

		// Act
		obj.SetDomain(fernTestValueDomain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}
