// Code generated by Fern. DO NOT EDIT.

package applepay

type ApplePaySessionRequest struct {
	ValidationURL *string `json:"validation_url,omitempty" url:"-"`
	DisplayName   *string `json:"display_name,omitempty" url:"-"`
	Domain        *string `json:"domain,omitempty" url:"-"`
}
