// Code generated by Fern. DO NOT EDIT.

package realtime

import (
	context "context"
	os "os"

	basistheory "github.com/Basis-Theory/go-sdk/v7"
	accountupdater "github.com/Basis-Theory/go-sdk/v7/accountupdater"
	core "github.com/Basis-Theory/go-sdk/v7/core"
	internal "github.com/Basis-Theory/go-sdk/v7/internal"
	option "github.com/Basis-Theory/go-sdk/v7/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns the update result
func (c *Client) Invoke(
	ctx context.Context,
	request *accountupdater.AccountUpdaterRealTimeRequest,
	opts ...option.RequestOption,
) (*basistheory.AccountUpdaterRealTimeResponse, error) {
	response, err := c.WithRawResponse.Invoke(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
