// Code generated by Fern. DO NOT EDIT.

package documents

import (
	basistheory "github.com/Basis-Theory/go-sdk/v7"
	core "github.com/Basis-Theory/go-sdk/v7/core"
	internal "github.com/Basis-Theory/go-sdk/v7/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	401: func(apiError *core.APIError) error {
		return &basistheory.UnauthorizedError{
			APIError: apiError,
		}
	},
	403: func(apiError *core.APIError) error {
		return &basistheory.ForbiddenError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &basistheory.NotFoundError{
			APIError: apiError,
		}
	},
}
