// Code generated by Fern. DO NOT EDIT.

package verify

import (
	context "context"
	v5 "github.com/Basis-Theory/go-sdk/v5"
	instructions "github.com/Basis-Theory/go-sdk/v5/agentic/agents/instructions"
	core "github.com/Basis-Theory/go-sdk/v5/core"
	internal "github.com/Basis-Theory/go-sdk/v5/internal"
	option "github.com/Basis-Theory/go-sdk/v5/option"
	http "net/http"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Initiate cardholder verification for a purchase instruction that requires it.
func (c *Client) Start(
	ctx context.Context,
	agentID string,
	instructionID string,
	request *v5.StartVerificationRequest,
	opts ...option.RequestOption,
) (*v5.VerificationResponse, error) {
	response, err := c.WithRawResponse.Start(
		ctx,
		agentID,
		instructionID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submit passkey/FIDO assertion data to complete instruction verification.
func (c *Client) Passkey(
	ctx context.Context,
	agentID string,
	instructionID string,
	request *instructions.SubmitPasskeyRequest,
	opts ...option.RequestOption,
) (*v5.Instruction, error) {
	response, err := c.WithRawResponse.Passkey(
		ctx,
		agentID,
		instructionID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
