// This file was auto-generated by Fern from our API Definition.

package basistheory

type ApplicationKeysListRequest struct {
	ID   []*string `json:"-" url:"id,omitempty"`
	Type []*string `json:"-" url:"type,omitempty"`
}
