// Code generated by Fern. DO NOT EDIT.

package basistheory

// Environments defines all of the API environments.
// These values can be used with the WithBaseURL
// RequestOption to override the client's default environment,
// if any.
var Environments = struct {
	Default string
	Us      string
	Eu      string
	Test    string
}{
	Default: "https://api.basistheory.com",
	Us:      "https://api.basistheory.com",
	Eu:      "https://api.basistheory.com",
	Test:    "https://api.test.basistheory.com",
}
