// Code generated by Fern. DO NOT EDIT.

package basistheory

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersCreateNetworkTokenRequest(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueData *Card
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTokenID", func(t *testing.T) {
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueTokenID *string
		obj.SetTokenID(fernTestValueTokenID)
		assert.Equal(t, fernTestValueTokenID, obj.TokenID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTokenIntentID", func(t *testing.T) {
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueTokenIntentID *string
		obj.SetTokenIntentID(fernTestValueTokenIntentID)
		assert.Equal(t, fernTestValueTokenIntentID, obj.TokenIntentID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpirationMonth", func(t *testing.T) {
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueExpirationMonth *int
		obj.SetExpirationMonth(fernTestValueExpirationMonth)
		assert.Equal(t, fernTestValueExpirationMonth, obj.ExpirationMonth)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpirationYear", func(t *testing.T) {
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueExpirationYear *int
		obj.SetExpirationYear(fernTestValueExpirationYear)
		assert.Equal(t, fernTestValueExpirationYear, obj.ExpirationYear)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCardholderInfo", func(t *testing.T) {
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueCardholderInfo *CardholderInfo
		obj.SetCardholderInfo(fernTestValueCardholderInfo)
		assert.Equal(t, fernTestValueCardholderInfo, obj.CardholderInfo)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMerchantID", func(t *testing.T) {
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueMerchantID *string
		obj.SetMerchantID(fernTestValueMerchantID)
		assert.Equal(t, fernTestValueMerchantID, obj.MerchantID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateNetworkTokenRequest(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueData *Card

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTokenID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueTokenID *string

		// Act
		obj.SetTokenID(fernTestValueTokenID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTokenIntentID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueTokenIntentID *string

		// Act
		obj.SetTokenIntentID(fernTestValueTokenIntentID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpirationMonth_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueExpirationMonth *int

		// Act
		obj.SetExpirationMonth(fernTestValueExpirationMonth)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpirationYear_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueExpirationYear *int

		// Act
		obj.SetExpirationYear(fernTestValueExpirationYear)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCardholderInfo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueCardholderInfo *CardholderInfo

		// Act
		obj.SetCardholderInfo(fernTestValueCardholderInfo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMerchantID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateNetworkTokenRequest{}
		var fernTestValueMerchantID *string

		// Act
		obj.SetMerchantID(fernTestValueMerchantID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAddress(t *testing.T) {
	t.Run("SetLine1", func(t *testing.T) {
		obj := &Address{}
		var fernTestValueLine1 *string
		obj.SetLine1(fernTestValueLine1)
		assert.Equal(t, fernTestValueLine1, obj.Line1)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLine2", func(t *testing.T) {
		obj := &Address{}
		var fernTestValueLine2 *string
		obj.SetLine2(fernTestValueLine2)
		assert.Equal(t, fernTestValueLine2, obj.Line2)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLine3", func(t *testing.T) {
		obj := &Address{}
		var fernTestValueLine3 *string
		obj.SetLine3(fernTestValueLine3)
		assert.Equal(t, fernTestValueLine3, obj.Line3)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPostalCode", func(t *testing.T) {
		obj := &Address{}
		var fernTestValuePostalCode *string
		obj.SetPostalCode(fernTestValuePostalCode)
		assert.Equal(t, fernTestValuePostalCode, obj.PostalCode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCity", func(t *testing.T) {
		obj := &Address{}
		var fernTestValueCity *string
		obj.SetCity(fernTestValueCity)
		assert.Equal(t, fernTestValueCity, obj.City)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStateCode", func(t *testing.T) {
		obj := &Address{}
		var fernTestValueStateCode *string
		obj.SetStateCode(fernTestValueStateCode)
		assert.Equal(t, fernTestValueStateCode, obj.StateCode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCountryCode", func(t *testing.T) {
		obj := &Address{}
		var fernTestValueCountryCode *string
		obj.SetCountryCode(fernTestValueCountryCode)
		assert.Equal(t, fernTestValueCountryCode, obj.CountryCode)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAddress(t *testing.T) {
	t.Run("GetLine1", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var expected *string
		obj.Line1 = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLine1(), "getter should return the property value")
	})

	t.Run("GetLine1_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		obj.Line1 = nil

		// Act & Assert
		assert.Nil(t, obj.GetLine1(), "getter should return nil when property is nil")
	})

	t.Run("GetLine1_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Address
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLine1() // Should return zero value
	})

	t.Run("GetLine2", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var expected *string
		obj.Line2 = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLine2(), "getter should return the property value")
	})

	t.Run("GetLine2_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		obj.Line2 = nil

		// Act & Assert
		assert.Nil(t, obj.GetLine2(), "getter should return nil when property is nil")
	})

	t.Run("GetLine2_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Address
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLine2() // Should return zero value
	})

	t.Run("GetLine3", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var expected *string
		obj.Line3 = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLine3(), "getter should return the property value")
	})

	t.Run("GetLine3_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		obj.Line3 = nil

		// Act & Assert
		assert.Nil(t, obj.GetLine3(), "getter should return nil when property is nil")
	})

	t.Run("GetLine3_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Address
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLine3() // Should return zero value
	})

	t.Run("GetPostalCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var expected *string
		obj.PostalCode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPostalCode(), "getter should return the property value")
	})

	t.Run("GetPostalCode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		obj.PostalCode = nil

		// Act & Assert
		assert.Nil(t, obj.GetPostalCode(), "getter should return nil when property is nil")
	})

	t.Run("GetPostalCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Address
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPostalCode() // Should return zero value
	})

	t.Run("GetCity", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var expected *string
		obj.City = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCity(), "getter should return the property value")
	})

	t.Run("GetCity_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		obj.City = nil

		// Act & Assert
		assert.Nil(t, obj.GetCity(), "getter should return nil when property is nil")
	})

	t.Run("GetCity_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Address
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCity() // Should return zero value
	})

	t.Run("GetStateCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var expected *string
		obj.StateCode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStateCode(), "getter should return the property value")
	})

	t.Run("GetStateCode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		obj.StateCode = nil

		// Act & Assert
		assert.Nil(t, obj.GetStateCode(), "getter should return nil when property is nil")
	})

	t.Run("GetStateCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Address
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStateCode() // Should return zero value
	})

	t.Run("GetCountryCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var expected *string
		obj.CountryCode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCountryCode(), "getter should return the property value")
	})

	t.Run("GetCountryCode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		obj.CountryCode = nil

		// Act & Assert
		assert.Nil(t, obj.GetCountryCode(), "getter should return nil when property is nil")
	})

	t.Run("GetCountryCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Address
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCountryCode() // Should return zero value
	})

}

func TestSettersMarkExplicitAddress(t *testing.T) {
	t.Run("SetLine1_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var fernTestValueLine1 *string

		// Act
		obj.SetLine1(fernTestValueLine1)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLine2_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var fernTestValueLine2 *string

		// Act
		obj.SetLine2(fernTestValueLine2)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLine3_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var fernTestValueLine3 *string

		// Act
		obj.SetLine3(fernTestValueLine3)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPostalCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var fernTestValuePostalCode *string

		// Act
		obj.SetPostalCode(fernTestValuePostalCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCity_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var fernTestValueCity *string

		// Act
		obj.SetCity(fernTestValueCity)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStateCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var fernTestValueStateCode *string

		// Act
		obj.SetStateCode(fernTestValueStateCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCountryCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}
		var fernTestValueCountryCode *string

		// Act
		obj.SetCountryCode(fernTestValueCountryCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCard(t *testing.T) {
	t.Run("SetNumber", func(t *testing.T) {
		obj := &Card{}
		var fernTestValueNumber *string
		obj.SetNumber(fernTestValueNumber)
		assert.Equal(t, fernTestValueNumber, obj.Number)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpirationMonth", func(t *testing.T) {
		obj := &Card{}
		var fernTestValueExpirationMonth *int
		obj.SetExpirationMonth(fernTestValueExpirationMonth)
		assert.Equal(t, fernTestValueExpirationMonth, obj.ExpirationMonth)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpirationYear", func(t *testing.T) {
		obj := &Card{}
		var fernTestValueExpirationYear *int
		obj.SetExpirationYear(fernTestValueExpirationYear)
		assert.Equal(t, fernTestValueExpirationYear, obj.ExpirationYear)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCvc", func(t *testing.T) {
		obj := &Card{}
		var fernTestValueCvc *string
		obj.SetCvc(fernTestValueCvc)
		assert.Equal(t, fernTestValueCvc, obj.Cvc)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCard(t *testing.T) {
	t.Run("GetNumber", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		var expected *string
		obj.Number = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNumber(), "getter should return the property value")
	})

	t.Run("GetNumber_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		obj.Number = nil

		// Act & Assert
		assert.Nil(t, obj.GetNumber(), "getter should return nil when property is nil")
	})

	t.Run("GetNumber_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Card
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNumber() // Should return zero value
	})

	t.Run("GetExpirationMonth", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		var expected *int
		obj.ExpirationMonth = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExpirationMonth(), "getter should return the property value")
	})

	t.Run("GetExpirationMonth_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		obj.ExpirationMonth = nil

		// Act & Assert
		assert.Nil(t, obj.GetExpirationMonth(), "getter should return nil when property is nil")
	})

	t.Run("GetExpirationMonth_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Card
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExpirationMonth() // Should return zero value
	})

	t.Run("GetExpirationYear", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		var expected *int
		obj.ExpirationYear = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExpirationYear(), "getter should return the property value")
	})

	t.Run("GetExpirationYear_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		obj.ExpirationYear = nil

		// Act & Assert
		assert.Nil(t, obj.GetExpirationYear(), "getter should return nil when property is nil")
	})

	t.Run("GetExpirationYear_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Card
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExpirationYear() // Should return zero value
	})

	t.Run("GetCvc", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		var expected *string
		obj.Cvc = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCvc(), "getter should return the property value")
	})

	t.Run("GetCvc_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		obj.Cvc = nil

		// Act & Assert
		assert.Nil(t, obj.GetCvc(), "getter should return nil when property is nil")
	})

	t.Run("GetCvc_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Card
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCvc() // Should return zero value
	})

}

func TestSettersMarkExplicitCard(t *testing.T) {
	t.Run("SetNumber_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		var fernTestValueNumber *string

		// Act
		obj.SetNumber(fernTestValueNumber)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpirationMonth_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		var fernTestValueExpirationMonth *int

		// Act
		obj.SetExpirationMonth(fernTestValueExpirationMonth)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpirationYear_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		var fernTestValueExpirationYear *int

		// Act
		obj.SetExpirationYear(fernTestValueExpirationYear)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCvc_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}
		var fernTestValueCvc *string

		// Act
		obj.SetCvc(fernTestValueCvc)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCardholderInfo(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &CardholderInfo{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAddress", func(t *testing.T) {
		obj := &CardholderInfo{}
		var fernTestValueAddress *Address
		obj.SetAddress(fernTestValueAddress)
		assert.Equal(t, fernTestValueAddress, obj.Address)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCardholderInfo(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CardholderInfo{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CardholderInfo{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CardholderInfo
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetAddress", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CardholderInfo{}
		var expected *Address
		obj.Address = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAddress(), "getter should return the property value")
	})

	t.Run("GetAddress_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CardholderInfo{}
		obj.Address = nil

		// Act & Assert
		assert.Nil(t, obj.GetAddress(), "getter should return nil when property is nil")
	})

	t.Run("GetAddress_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CardholderInfo
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAddress() // Should return zero value
	})

}

func TestSettersMarkExplicitCardholderInfo(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CardholderInfo{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAddress_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CardholderInfo{}
		var fernTestValueAddress *Address

		// Act
		obj.SetAddress(fernTestValueAddress)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersNetworkToken(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTenantID", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueTenantID *string
		obj.SetTenantID(fernTestValueTenantID)
		assert.Equal(t, fernTestValueTenantID, obj.TenantID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetData", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueData *Card
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCard", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueCard *CardDetails
		obj.SetCard(fernTestValueCard)
		assert.Equal(t, fernTestValueCard, obj.Card)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNetworkToken", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueNetworkToken *CardDetails
		obj.SetNetworkToken(fernTestValueNetworkToken)
		assert.Equal(t, fernTestValueNetworkToken, obj.NetworkToken)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPar", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValuePar *string
		obj.SetPar(fernTestValuePar)
		assert.Equal(t, fernTestValuePar, obj.Par)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueStatus *string
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedBy", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueCreatedBy *string
		obj.SetCreatedBy(fernTestValueCreatedBy)
		assert.Equal(t, fernTestValueCreatedBy, obj.CreatedBy)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueCreatedAt *time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetModifiedBy", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueModifiedBy *string
		obj.SetModifiedBy(fernTestValueModifiedBy)
		assert.Equal(t, fernTestValueModifiedBy, obj.ModifiedBy)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetModifiedAt", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueModifiedAt *time.Time
		obj.SetModifiedAt(fernTestValueModifiedAt)
		assert.Equal(t, fernTestValueModifiedAt, obj.ModifiedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTokenID", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueTokenID *string
		obj.SetTokenID(fernTestValueTokenID)
		assert.Equal(t, fernTestValueTokenID, obj.TokenID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTokenIntentID", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueTokenIntentID *string
		obj.SetTokenIntentID(fernTestValueTokenIntentID)
		assert.Equal(t, fernTestValueTokenIntentID, obj.TokenIntentID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExtras", func(t *testing.T) {
		obj := &NetworkToken{}
		var fernTestValueExtras *NetworkTokenExtras
		obj.SetExtras(fernTestValueExtras)
		assert.Equal(t, fernTestValueExtras, obj.Extras)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersNetworkToken(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetTenantID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *string
		obj.TenantID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTenantID(), "getter should return the property value")
	})

	t.Run("GetTenantID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.TenantID = nil

		// Act & Assert
		assert.Nil(t, obj.GetTenantID(), "getter should return nil when property is nil")
	})

	t.Run("GetTenantID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTenantID() // Should return zero value
	})

	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *Card
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetCard", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *CardDetails
		obj.Card = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCard(), "getter should return the property value")
	})

	t.Run("GetCard_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.Card = nil

		// Act & Assert
		assert.Nil(t, obj.GetCard(), "getter should return nil when property is nil")
	})

	t.Run("GetCard_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCard() // Should return zero value
	})

	t.Run("GetNetworkToken", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *CardDetails
		obj.NetworkToken = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNetworkToken(), "getter should return the property value")
	})

	t.Run("GetNetworkToken_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.NetworkToken = nil

		// Act & Assert
		assert.Nil(t, obj.GetNetworkToken(), "getter should return nil when property is nil")
	})

	t.Run("GetNetworkToken_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNetworkToken() // Should return zero value
	})

	t.Run("GetPar", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *string
		obj.Par = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPar(), "getter should return the property value")
	})

	t.Run("GetPar_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.Par = nil

		// Act & Assert
		assert.Nil(t, obj.GetPar(), "getter should return nil when property is nil")
	})

	t.Run("GetPar_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPar() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *string
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.Status = nil

		// Act & Assert
		assert.Nil(t, obj.GetStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetCreatedBy", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *string
		obj.CreatedBy = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedBy(), "getter should return the property value")
	})

	t.Run("GetCreatedBy_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.CreatedBy = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedBy(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedBy_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedBy() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.CreatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetModifiedBy", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *string
		obj.ModifiedBy = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetModifiedBy(), "getter should return the property value")
	})

	t.Run("GetModifiedBy_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.ModifiedBy = nil

		// Act & Assert
		assert.Nil(t, obj.GetModifiedBy(), "getter should return nil when property is nil")
	})

	t.Run("GetModifiedBy_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetModifiedBy() // Should return zero value
	})

	t.Run("GetModifiedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *time.Time
		obj.ModifiedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetModifiedAt(), "getter should return the property value")
	})

	t.Run("GetModifiedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.ModifiedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetModifiedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetModifiedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetModifiedAt() // Should return zero value
	})

	t.Run("GetTokenID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *string
		obj.TokenID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTokenID(), "getter should return the property value")
	})

	t.Run("GetTokenID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.TokenID = nil

		// Act & Assert
		assert.Nil(t, obj.GetTokenID(), "getter should return nil when property is nil")
	})

	t.Run("GetTokenID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTokenID() // Should return zero value
	})

	t.Run("GetTokenIntentID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *string
		obj.TokenIntentID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTokenIntentID(), "getter should return the property value")
	})

	t.Run("GetTokenIntentID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.TokenIntentID = nil

		// Act & Assert
		assert.Nil(t, obj.GetTokenIntentID(), "getter should return nil when property is nil")
	})

	t.Run("GetTokenIntentID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTokenIntentID() // Should return zero value
	})

	t.Run("GetExtras", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var expected *NetworkTokenExtras
		obj.Extras = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExtras(), "getter should return the property value")
	})

	t.Run("GetExtras_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		obj.Extras = nil

		// Act & Assert
		assert.Nil(t, obj.GetExtras(), "getter should return nil when property is nil")
	})

	t.Run("GetExtras_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExtras() // Should return zero value
	})

}

func TestSettersMarkExplicitNetworkToken(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTenantID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueTenantID *string

		// Act
		obj.SetTenantID(fernTestValueTenantID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueData *Card

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCard_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueCard *CardDetails

		// Act
		obj.SetCard(fernTestValueCard)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNetworkToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueNetworkToken *CardDetails

		// Act
		obj.SetNetworkToken(fernTestValueNetworkToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPar_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValuePar *string

		// Act
		obj.SetPar(fernTestValuePar)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueStatus *string

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedBy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueCreatedBy *string

		// Act
		obj.SetCreatedBy(fernTestValueCreatedBy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueCreatedAt *time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetModifiedBy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueModifiedBy *string

		// Act
		obj.SetModifiedBy(fernTestValueModifiedBy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetModifiedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueModifiedAt *time.Time

		// Act
		obj.SetModifiedAt(fernTestValueModifiedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTokenID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueTokenID *string

		// Act
		obj.SetTokenID(fernTestValueTokenID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTokenIntentID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueTokenIntentID *string

		// Act
		obj.SetTokenIntentID(fernTestValueTokenIntentID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExtras_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}
		var fernTestValueExtras *NetworkTokenExtras

		// Act
		obj.SetExtras(fernTestValueExtras)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersNetworkTokenCryptogram(t *testing.T) {
	t.Run("SetCryptogram", func(t *testing.T) {
		obj := &NetworkTokenCryptogram{}
		var fernTestValueCryptogram *string
		obj.SetCryptogram(fernTestValueCryptogram)
		assert.Equal(t, fernTestValueCryptogram, obj.Cryptogram)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEci", func(t *testing.T) {
		obj := &NetworkTokenCryptogram{}
		var fernTestValueEci *string
		obj.SetEci(fernTestValueEci)
		assert.Equal(t, fernTestValueEci, obj.Eci)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersNetworkTokenCryptogram(t *testing.T) {
	t.Run("GetCryptogram", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenCryptogram{}
		var expected *string
		obj.Cryptogram = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCryptogram(), "getter should return the property value")
	})

	t.Run("GetCryptogram_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenCryptogram{}
		obj.Cryptogram = nil

		// Act & Assert
		assert.Nil(t, obj.GetCryptogram(), "getter should return nil when property is nil")
	})

	t.Run("GetCryptogram_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkTokenCryptogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCryptogram() // Should return zero value
	})

	t.Run("GetEci", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenCryptogram{}
		var expected *string
		obj.Eci = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEci(), "getter should return the property value")
	})

	t.Run("GetEci_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenCryptogram{}
		obj.Eci = nil

		// Act & Assert
		assert.Nil(t, obj.GetEci(), "getter should return nil when property is nil")
	})

	t.Run("GetEci_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkTokenCryptogram
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEci() // Should return zero value
	})

}

func TestSettersMarkExplicitNetworkTokenCryptogram(t *testing.T) {
	t.Run("SetCryptogram_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenCryptogram{}
		var fernTestValueCryptogram *string

		// Act
		obj.SetCryptogram(fernTestValueCryptogram)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEci_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenCryptogram{}
		var fernTestValueEci *string

		// Act
		obj.SetEci(fernTestValueEci)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersNetworkTokenExtras(t *testing.T) {
	t.Run("SetDeduplicated", func(t *testing.T) {
		obj := &NetworkTokenExtras{}
		var fernTestValueDeduplicated *bool
		obj.SetDeduplicated(fernTestValueDeduplicated)
		assert.Equal(t, fernTestValueDeduplicated, obj.Deduplicated)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersNetworkTokenExtras(t *testing.T) {
	t.Run("GetDeduplicated", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenExtras{}
		var expected *bool
		obj.Deduplicated = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDeduplicated(), "getter should return the property value")
	})

	t.Run("GetDeduplicated_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenExtras{}
		obj.Deduplicated = nil

		// Act & Assert
		assert.Nil(t, obj.GetDeduplicated(), "getter should return nil when property is nil")
	})

	t.Run("GetDeduplicated_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkTokenExtras
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDeduplicated() // Should return zero value
	})

}

func TestSettersMarkExplicitNetworkTokenExtras(t *testing.T) {
	t.Run("SetDeduplicated_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenExtras{}
		var fernTestValueDeduplicated *bool

		// Act
		obj.SetDeduplicated(fernTestValueDeduplicated)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingAddress(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Address{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Address
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Address
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Address
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCard(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Card{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Card
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Card
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Card
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCardholderInfo(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CardholderInfo{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CardholderInfo
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CardholderInfo
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CardholderInfo
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingNetworkToken(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkToken{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled NetworkToken
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj NetworkToken
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj NetworkToken
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingNetworkTokenCryptogram(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenCryptogram{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled NetworkTokenCryptogram
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj NetworkTokenCryptogram
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj NetworkTokenCryptogram
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingNetworkTokenExtras(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NetworkTokenExtras{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled NetworkTokenExtras
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj NetworkTokenExtras
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj NetworkTokenExtras
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringAddress(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Address{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Address
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCard(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Card{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Card
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCardholderInfo(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CardholderInfo{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CardholderInfo
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringNetworkToken(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &NetworkToken{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringNetworkTokenCryptogram(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &NetworkTokenCryptogram{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkTokenCryptogram
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringNetworkTokenExtras(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &NetworkTokenExtras{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkTokenExtras
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesAddress(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Address{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Address
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCard(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Card{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Card
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCardholderInfo(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CardholderInfo{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CardholderInfo
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesNetworkToken(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &NetworkToken{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkToken
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesNetworkTokenCryptogram(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &NetworkTokenCryptogram{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkTokenCryptogram
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesNetworkTokenExtras(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &NetworkTokenExtras{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NetworkTokenExtras
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
