// Code generated by Fern. DO NOT EDIT.

package basistheory

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Basis-Theory/go-sdk/v4/internal"
	time "time"
)

type CreateReactorRequest struct {
	Name          string             `json:"name" url:"-"`
	Code          string             `json:"code" url:"-"`
	Application   *Application       `json:"application,omitempty" url:"-"`
	Configuration map[string]*string `json:"configuration,omitempty" url:"-"`
	Runtime       *Runtime           `json:"runtime,omitempty" url:"-"`
}

type ReactorsListRequest struct {
	ID    []*string `json:"-" url:"id,omitempty"`
	Name  *string   `json:"-" url:"name,omitempty"`
	Page  *int      `json:"-" url:"page,omitempty"`
	Start *string   `json:"-" url:"start,omitempty"`
	Size  *int      `json:"-" url:"size,omitempty"`
}

type PatchReactorRequest struct {
	Name          *string            `json:"name,omitempty" url:"-"`
	Application   *Application       `json:"application,omitempty" url:"-"`
	Code          *string            `json:"code,omitempty" url:"-"`
	Configuration map[string]*string `json:"configuration,omitempty" url:"-"`
	Runtime       *Runtime           `json:"runtime,omitempty" url:"-"`
}

type ReactRequest struct {
	Args        interface{} `json:"args,omitempty" url:"-"`
	CallbackURL *string     `json:"callback_url,omitempty" url:"-"`
}

type ReactRequestAsync struct {
	Args interface{} `json:"args,omitempty" url:"-"`
}

type AsyncReactResponse struct {
	AsyncReactorRequestID *string `json:"asyncReactorRequestId,omitempty" url:"asyncReactorRequestId,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AsyncReactResponse) GetAsyncReactorRequestID() *string {
	if a == nil {
		return nil
	}
	return a.AsyncReactorRequestID
}

func (a *AsyncReactResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AsyncReactResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AsyncReactResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AsyncReactResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AsyncReactResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type ReactResponse struct {
	Tokens  interface{} `json:"tokens,omitempty" url:"tokens,omitempty"`
	Raw     interface{} `json:"raw,omitempty" url:"raw,omitempty"`
	Body    interface{} `json:"body,omitempty" url:"body,omitempty"`
	Headers interface{} `json:"headers,omitempty" url:"headers,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReactResponse) GetTokens() interface{} {
	if r == nil {
		return nil
	}
	return r.Tokens
}

func (r *ReactResponse) GetRaw() interface{} {
	if r == nil {
		return nil
	}
	return r.Raw
}

func (r *ReactResponse) GetBody() interface{} {
	if r == nil {
		return nil
	}
	return r.Body
}

func (r *ReactResponse) GetHeaders() interface{} {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *ReactResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ReactResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReactResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReactResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReactResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type Reactor struct {
	ID            *string            `json:"id,omitempty" url:"id,omitempty"`
	TenantID      *string            `json:"tenant_id,omitempty" url:"tenant_id,omitempty"`
	Name          *string            `json:"name,omitempty" url:"name,omitempty"`
	Formula       *ReactorFormula    `json:"formula,omitempty" url:"formula,omitempty"`
	State         *string            `json:"state,omitempty" url:"state,omitempty"`
	Code          *string            `json:"code,omitempty" url:"code,omitempty"`
	Application   *Application       `json:"application,omitempty" url:"application,omitempty"`
	CreatedBy     *string            `json:"created_by,omitempty" url:"created_by,omitempty"`
	CreatedAt     *time.Time         `json:"created_at,omitempty" url:"created_at,omitempty"`
	ModifiedBy    *string            `json:"modified_by,omitempty" url:"modified_by,omitempty"`
	ModifiedAt    *time.Time         `json:"modified_at,omitempty" url:"modified_at,omitempty"`
	Configuration map[string]*string `json:"configuration,omitempty" url:"configuration,omitempty"`
	Runtime       *Runtime           `json:"runtime,omitempty" url:"runtime,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *Reactor) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *Reactor) GetTenantID() *string {
	if r == nil {
		return nil
	}
	return r.TenantID
}

func (r *Reactor) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *Reactor) GetFormula() *ReactorFormula {
	if r == nil {
		return nil
	}
	return r.Formula
}

func (r *Reactor) GetState() *string {
	if r == nil {
		return nil
	}
	return r.State
}

func (r *Reactor) GetCode() *string {
	if r == nil {
		return nil
	}
	return r.Code
}

func (r *Reactor) GetApplication() *Application {
	if r == nil {
		return nil
	}
	return r.Application
}

func (r *Reactor) GetCreatedBy() *string {
	if r == nil {
		return nil
	}
	return r.CreatedBy
}

func (r *Reactor) GetCreatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *Reactor) GetModifiedBy() *string {
	if r == nil {
		return nil
	}
	return r.ModifiedBy
}

func (r *Reactor) GetModifiedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.ModifiedAt
}

func (r *Reactor) GetConfiguration() map[string]*string {
	if r == nil {
		return nil
	}
	return r.Configuration
}

func (r *Reactor) GetRuntime() *Runtime {
	if r == nil {
		return nil
	}
	return r.Runtime
}

func (r *Reactor) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *Reactor) UnmarshalJSON(data []byte) error {
	type embed Reactor
	var unmarshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"created_at,omitempty"`
		ModifiedAt *internal.DateTime `json:"modified_at,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = Reactor(unmarshaler.embed)
	r.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	r.ModifiedAt = unmarshaler.ModifiedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *Reactor) MarshalJSON() ([]byte, error) {
	type embed Reactor
	var marshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"created_at,omitempty"`
		ModifiedAt *internal.DateTime `json:"modified_at,omitempty"`
	}{
		embed:      embed(*r),
		CreatedAt:  internal.NewOptionalDateTime(r.CreatedAt),
		ModifiedAt: internal.NewOptionalDateTime(r.ModifiedAt),
	}
	return json.Marshal(marshaler)
}

func (r *Reactor) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReactorFormula struct {
	ID                *string                           `json:"id,omitempty" url:"id,omitempty"`
	Type              *string                           `json:"type,omitempty" url:"type,omitempty"`
	Status            *string                           `json:"status,omitempty" url:"status,omitempty"`
	Name              *string                           `json:"name,omitempty" url:"name,omitempty"`
	Description       *string                           `json:"description,omitempty" url:"description,omitempty"`
	Icon              *string                           `json:"icon,omitempty" url:"icon,omitempty"`
	Code              *string                           `json:"code,omitempty" url:"code,omitempty"`
	CreatedBy         *string                           `json:"created_by,omitempty" url:"created_by,omitempty"`
	CreatedAt         *time.Time                        `json:"created_at,omitempty" url:"created_at,omitempty"`
	ModifiedBy        *string                           `json:"modified_by,omitempty" url:"modified_by,omitempty"`
	ModifiedAt        *time.Time                        `json:"modified_at,omitempty" url:"modified_at,omitempty"`
	Configuration     []*ReactorFormulaConfiguration    `json:"configuration,omitempty" url:"configuration,omitempty"`
	RequestParameters []*ReactorFormulaRequestParameter `json:"request_parameters,omitempty" url:"request_parameters,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReactorFormula) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *ReactorFormula) GetType() *string {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *ReactorFormula) GetStatus() *string {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *ReactorFormula) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *ReactorFormula) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReactorFormula) GetIcon() *string {
	if r == nil {
		return nil
	}
	return r.Icon
}

func (r *ReactorFormula) GetCode() *string {
	if r == nil {
		return nil
	}
	return r.Code
}

func (r *ReactorFormula) GetCreatedBy() *string {
	if r == nil {
		return nil
	}
	return r.CreatedBy
}

func (r *ReactorFormula) GetCreatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *ReactorFormula) GetModifiedBy() *string {
	if r == nil {
		return nil
	}
	return r.ModifiedBy
}

func (r *ReactorFormula) GetModifiedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.ModifiedAt
}

func (r *ReactorFormula) GetConfiguration() []*ReactorFormulaConfiguration {
	if r == nil {
		return nil
	}
	return r.Configuration
}

func (r *ReactorFormula) GetRequestParameters() []*ReactorFormulaRequestParameter {
	if r == nil {
		return nil
	}
	return r.RequestParameters
}

func (r *ReactorFormula) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ReactorFormula) UnmarshalJSON(data []byte) error {
	type embed ReactorFormula
	var unmarshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"created_at,omitempty"`
		ModifiedAt *internal.DateTime `json:"modified_at,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = ReactorFormula(unmarshaler.embed)
	r.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	r.ModifiedAt = unmarshaler.ModifiedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReactorFormula) MarshalJSON() ([]byte, error) {
	type embed ReactorFormula
	var marshaler = struct {
		embed
		CreatedAt  *internal.DateTime `json:"created_at,omitempty"`
		ModifiedAt *internal.DateTime `json:"modified_at,omitempty"`
	}{
		embed:      embed(*r),
		CreatedAt:  internal.NewOptionalDateTime(r.CreatedAt),
		ModifiedAt: internal.NewOptionalDateTime(r.ModifiedAt),
	}
	return json.Marshal(marshaler)
}

func (r *ReactorFormula) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReactorFormulaConfiguration struct {
	Name        string  `json:"name" url:"name"`
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	Type        string  `json:"type" url:"type"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReactorFormulaConfiguration) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *ReactorFormulaConfiguration) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReactorFormulaConfiguration) GetType() string {
	if r == nil {
		return ""
	}
	return r.Type
}

func (r *ReactorFormulaConfiguration) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ReactorFormulaConfiguration) UnmarshalJSON(data []byte) error {
	type unmarshaler ReactorFormulaConfiguration
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReactorFormulaConfiguration(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReactorFormulaConfiguration) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReactorFormulaRequestParameter struct {
	Name        string  `json:"name" url:"name"`
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	Type        string  `json:"type" url:"type"`
	Optional    *bool   `json:"optional,omitempty" url:"optional,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReactorFormulaRequestParameter) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *ReactorFormulaRequestParameter) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReactorFormulaRequestParameter) GetType() string {
	if r == nil {
		return ""
	}
	return r.Type
}

func (r *ReactorFormulaRequestParameter) GetOptional() *bool {
	if r == nil {
		return nil
	}
	return r.Optional
}

func (r *ReactorFormulaRequestParameter) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ReactorFormulaRequestParameter) UnmarshalJSON(data []byte) error {
	type unmarshaler ReactorFormulaRequestParameter
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReactorFormulaRequestParameter(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReactorFormulaRequestParameter) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReactorPaginatedList struct {
	Pagination *Pagination `json:"pagination,omitempty" url:"pagination,omitempty"`
	Data       []*Reactor  `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReactorPaginatedList) GetPagination() *Pagination {
	if r == nil {
		return nil
	}
	return r.Pagination
}

func (r *ReactorPaginatedList) GetData() []*Reactor {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ReactorPaginatedList) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *ReactorPaginatedList) UnmarshalJSON(data []byte) error {
	type unmarshaler ReactorPaginatedList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReactorPaginatedList(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReactorPaginatedList) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type UpdateReactorRequest struct {
	Name          string             `json:"name" url:"-"`
	Application   *Application       `json:"application,omitempty" url:"-"`
	Code          string             `json:"code" url:"-"`
	Configuration map[string]*string `json:"configuration,omitempty" url:"-"`
	Runtime       *Runtime           `json:"runtime,omitempty" url:"-"`
}
