// Code generated by Fern. DO NOT EDIT.

package threeds_sessions_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	basistheory "github.com/Basis-Theory/go-sdk/v5"
	client "github.com/Basis-Theory/go-sdk/v5/client"
	option "github.com/Basis-Theory/go-sdk/v5/option"
	threeds "github.com/Basis-Theory/go-sdk/v5/threeds"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestThreedsSessionsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &threeds.CreateThreeDsSessionRequest{}
	_, invocationErr := client.Threeds.Sessions.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreedsSessionsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreedsSessionsCreateWithWireMock", "POST", "/3ds/sessions", nil, 1)
}

func TestThreedsSessionsAuthenticateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &basistheory.AuthenticateThreeDsSessionRequest{
		AuthenticationCategory: "authentication_category",
		AuthenticationType:     "authentication_type",
	}
	_, invocationErr := client.Threeds.Sessions.Authenticate(
		context.TODO(),
		"sessionId",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreedsSessionsAuthenticateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreedsSessionsAuthenticateWithWireMock", "POST", "/3ds/sessions/sessionId/authenticate", nil, 1)
}

func TestThreedsSessionsGetChallengeResultWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	_, invocationErr := client.Threeds.Sessions.GetChallengeResult(
		context.TODO(),
		"sessionId",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreedsSessionsGetChallengeResultWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreedsSessionsGetChallengeResultWithWireMock", "GET", "/3ds/sessions/sessionId/challenge-result", nil, 1)
}

func TestThreedsSessionsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	_, invocationErr := client.Threeds.Sessions.Get(
		context.TODO(),
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreedsSessionsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreedsSessionsGetWithWireMock", "GET", "/3ds/sessions/id", nil, 1)
}
