// Code generated by Fern. DO NOT EDIT.

package apple_pay_merchant_certificates_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	merchant "github.com/Basis-Theory/go-sdk/v5/applepay/merchant"
	client "github.com/Basis-Theory/go-sdk/v5/client"
	option "github.com/Basis-Theory/go-sdk/v5/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestApplePayMerchantCertificatesGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	_, invocationErr := client.ApplePay.Merchant.Certificates.Get(
		context.TODO(),
		"merchantId",
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestApplePayMerchantCertificatesGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestApplePayMerchantCertificatesGetWithWireMock", "GET", "/apple-pay/merchant-registration/merchantId/certificates/id", nil, 1)
}

func TestApplePayMerchantCertificatesDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	invocationErr := client.ApplePay.Merchant.Certificates.Delete(
		context.TODO(),
		"merchantId",
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestApplePayMerchantCertificatesDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestApplePayMerchantCertificatesDeleteWithWireMock", "DELETE", "/apple-pay/merchant-registration/merchantId/certificates/id", nil, 1)
}

func TestApplePayMerchantCertificatesCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &merchant.ApplePayMerchantCertificatesRegisterRequest{
		PaymentProcessorCertificateData:     "payment_processor_certificate_data",
		PaymentProcessorCertificatePassword: "payment_processor_certificate_password",
	}
	_, invocationErr := client.ApplePay.Merchant.Certificates.Create(
		context.TODO(),
		"merchantId",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestApplePayMerchantCertificatesCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestApplePayMerchantCertificatesCreateWithWireMock", "POST", "/apple-pay/merchant-registration/merchantId/certificates", nil, 1)
}
