// Code generated by Fern. DO NOT EDIT.

package verify

import (
	context "context"
	http "net/http"

	basistheory "github.com/Basis-Theory/go-sdk/v6"
	enrollments "github.com/Basis-Theory/go-sdk/v6/agentic/enrollments"
	core "github.com/Basis-Theory/go-sdk/v6/core"
	internal "github.com/Basis-Theory/go-sdk/v6/internal"
	option "github.com/Basis-Theory/go-sdk/v6/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Start(
	ctx context.Context,
	enrollmentID string,
	request *basistheory.StartVerificationRequest,
	opts ...option.RequestOption,
) (*core.Response[*basistheory.VerificationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.basistheory.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agentic/enrollments/%v/verify",
		enrollmentID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *basistheory.VerificationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(enrollments.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*basistheory.VerificationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Method(
	ctx context.Context,
	enrollmentID string,
	request *enrollments.SelectMethodRequest,
	opts ...option.RequestOption,
) (*core.Response[*basistheory.VerificationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.basistheory.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agentic/enrollments/%v/verify/method",
		enrollmentID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *basistheory.VerificationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(enrollments.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*basistheory.VerificationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Otp(
	ctx context.Context,
	enrollmentID string,
	request *enrollments.SubmitOtpRequest,
	opts ...option.RequestOption,
) (*core.Response[*basistheory.VerificationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.basistheory.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agentic/enrollments/%v/verify/otp",
		enrollmentID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *basistheory.VerificationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(enrollments.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*basistheory.VerificationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Complete(
	ctx context.Context,
	enrollmentID string,
	request *enrollments.CompleteVerificationRequest,
	opts ...option.RequestOption,
) (*core.Response[*basistheory.VerificationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.basistheory.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agentic/enrollments/%v/verify/complete",
		enrollmentID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *basistheory.VerificationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(enrollments.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*basistheory.VerificationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
