// Code generated by Fern. DO NOT EDIT.

package applicationkeys

import (
	context "context"
	v4 "github.com/Basis-Theory/go-sdk/v4"
	core "github.com/Basis-Theory/go-sdk/v4/core"
	internal "github.com/Basis-Theory/go-sdk/v4/internal"
	option "github.com/Basis-Theory/go-sdk/v4/option"
	http "net/http"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

func (c *Client) List(
	ctx context.Context,
	id string,
	request *v4.ApplicationKeysListRequest,
	opts ...option.RequestOption,
) ([]*v4.ApplicationKey, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Create(
	ctx context.Context,
	id string,
	opts ...option.IdempotentRequestOption,
) (*v4.ApplicationKey, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	id string,
	keyID string,
	opts ...option.RequestOption,
) (*v4.ApplicationKey, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		keyID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	id string,
	keyID string,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		id,
		keyID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
