// Code generated by Fern. DO NOT EDIT.

package agentic

import (
	json "encoding/json"
	fmt "fmt"
	v7 "github.com/Basis-Theory/go-sdk/v7"
	internal "github.com/Basis-Theory/go-sdk/v7/internal"
	big "math/big"
	time "time"
)

var (
	createAllowanceRequestFieldBtIdempotencyKey = big.NewInt(1 << 0)
	createAllowanceRequestFieldPaymentMethodID  = big.NewInt(1 << 1)
	createAllowanceRequestFieldAgentID          = big.NewInt(1 << 2)
	createAllowanceRequestFieldAmount           = big.NewInt(1 << 3)
	createAllowanceRequestFieldMerchant         = big.NewInt(1 << 4)
	createAllowanceRequestFieldDescription      = big.NewInt(1 << 5)
	createAllowanceRequestFieldExpiresAt        = big.NewInt(1 << 6)
	createAllowanceRequestFieldMetadata         = big.NewInt(1 << 7)
)

type CreateAllowanceRequest struct {
	// Optional stable key for safely replaying this create request. Without it, every request creates a new allowance.
	BtIdempotencyKey *string `json:"-" url:"-"`
	PaymentMethodID  string  `json:"payment_method_id" url:"-"`
	// Optional attribution to an agent owned by the tenant. This does not authorize the caller; tenant API-key permissions remain the authorization boundary.
	AgentID *string                 `json:"agent_id,omitempty" url:"-"`
	Amount  *v7.SharedPaymentAmount `json:"amount" url:"-"`
	// Optional merchant the allowance is scoped to. Omit it to leave the allowance open and supply `merchant` on each credential request instead. Once set it cannot be changed, and a credential request for a merchant-scoped allowance must not send its own `merchant`.
	Merchant *v7.SharedPaymentMerchant `json:"merchant,omitempty" url:"-"`
	// Customer-facing prompt describing what the allowance permits.
	Description string `json:"description" url:"-"`
	// ISO 8601 timestamp when the allowance expires. Must be in the future.
	ExpiresAt time.Time `json:"expires_at" url:"-"`
	// Public integration metadata. The JSON-encoded value must not exceed 32 KiB.
	Metadata map[string]any `json:"metadata,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateAllowanceRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetBtIdempotencyKey sets the BtIdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAllowanceRequest) SetBtIdempotencyKey(btIdempotencyKey *string) {
	c.BtIdempotencyKey = btIdempotencyKey
	c.require(createAllowanceRequestFieldBtIdempotencyKey)
}

// SetPaymentMethodID sets the PaymentMethodID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAllowanceRequest) SetPaymentMethodID(paymentMethodID string) {
	c.PaymentMethodID = paymentMethodID
	c.require(createAllowanceRequestFieldPaymentMethodID)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAllowanceRequest) SetAgentID(agentID *string) {
	c.AgentID = agentID
	c.require(createAllowanceRequestFieldAgentID)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAllowanceRequest) SetAmount(amount *v7.SharedPaymentAmount) {
	c.Amount = amount
	c.require(createAllowanceRequestFieldAmount)
}

// SetMerchant sets the Merchant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAllowanceRequest) SetMerchant(merchant *v7.SharedPaymentMerchant) {
	c.Merchant = merchant
	c.require(createAllowanceRequestFieldMerchant)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAllowanceRequest) SetDescription(description string) {
	c.Description = description
	c.require(createAllowanceRequestFieldDescription)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAllowanceRequest) SetExpiresAt(expiresAt time.Time) {
	c.ExpiresAt = expiresAt
	c.require(createAllowanceRequestFieldExpiresAt)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAllowanceRequest) SetMetadata(metadata map[string]any) {
	c.Metadata = metadata
	c.require(createAllowanceRequestFieldMetadata)
}

func (c *CreateAllowanceRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateAllowanceRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateAllowanceRequest(body)
	return nil
}

func (c *CreateAllowanceRequest) MarshalJSON() ([]byte, error) {
	type embed CreateAllowanceRequest
	var marshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expires_at"`
	}{
		embed:     embed(*c),
		ExpiresAt: internal.NewDateTime(c.ExpiresAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	allowancesErrorsRequestFieldSize  = big.NewInt(1 << 0)
	allowancesErrorsRequestFieldStart = big.NewInt(1 << 1)
)

type AllowancesErrorsRequest struct {
	Size  *int    `json:"-" url:"size,omitempty"`
	Start *string `json:"-" url:"start,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AllowancesErrorsRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AllowancesErrorsRequest) SetSize(size *int) {
	a.Size = size
	a.require(allowancesErrorsRequestFieldSize)
}

// SetStart sets the Start field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AllowancesErrorsRequest) SetStart(start *string) {
	a.Start = start
	a.require(allowancesErrorsRequestFieldStart)
}

var (
	allowancesListRequestFieldSize            = big.NewInt(1 << 0)
	allowancesListRequestFieldStart           = big.NewInt(1 << 1)
	allowancesListRequestFieldPaymentMethodID = big.NewInt(1 << 2)
	allowancesListRequestFieldStatus          = big.NewInt(1 << 3)
)

type AllowancesListRequest struct {
	Size  *int    `json:"-" url:"size,omitempty"`
	Start *string `json:"-" url:"start,omitempty"`
	// Optional payment method ID to list its allowances.
	PaymentMethodID *string `json:"-" url:"payment_method_id,omitempty"`
	// Derived resource status filter. Defaults to active.
	Status *AllowancesListRequestStatus `json:"-" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AllowancesListRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AllowancesListRequest) SetSize(size *int) {
	a.Size = size
	a.require(allowancesListRequestFieldSize)
}

// SetStart sets the Start field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AllowancesListRequest) SetStart(start *string) {
	a.Start = start
	a.require(allowancesListRequestFieldStart)
}

// SetPaymentMethodID sets the PaymentMethodID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AllowancesListRequest) SetPaymentMethodID(paymentMethodID *string) {
	a.PaymentMethodID = paymentMethodID
	a.require(allowancesListRequestFieldPaymentMethodID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AllowancesListRequest) SetStatus(status *AllowancesListRequestStatus) {
	a.Status = status
	a.require(allowancesListRequestFieldStatus)
}

type AllowancesListRequestStatus string

const (
	AllowancesListRequestStatusActive    AllowancesListRequestStatus = "active"
	AllowancesListRequestStatusCancelled AllowancesListRequestStatus = "cancelled"
	AllowancesListRequestStatusExpired   AllowancesListRequestStatus = "expired"
	AllowancesListRequestStatusAll       AllowancesListRequestStatus = "all"
)

func NewAllowancesListRequestStatusFromString(s string) (AllowancesListRequestStatus, error) {
	switch s {
	case "active":
		return AllowancesListRequestStatusActive, nil
	case "cancelled":
		return AllowancesListRequestStatusCancelled, nil
	case "expired":
		return AllowancesListRequestStatusExpired, nil
	case "all":
		return AllowancesListRequestStatusAll, nil
	}
	var t AllowancesListRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AllowancesListRequestStatus) Ptr() *AllowancesListRequestStatus {
	return &a
}

var (
	allowancesUpdateRequestFieldAmount      = big.NewInt(1 << 0)
	allowancesUpdateRequestFieldDescription = big.NewInt(1 << 1)
	allowancesUpdateRequestFieldExpiresAt   = big.NewInt(1 << 2)
)

type AllowancesUpdateRequest struct {
	Amount *v7.SharedPaymentAmount `json:"amount,omitempty" url:"-"`
	// Customer-facing prompt describing what the allowance permits.
	Description *string `json:"description,omitempty" url:"-"`
	// ISO 8601 timestamp when the allowance expires. Must be in the future.
	ExpiresAt *time.Time `json:"expires_at,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AllowancesUpdateRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AllowancesUpdateRequest) SetAmount(amount *v7.SharedPaymentAmount) {
	a.Amount = amount
	a.require(allowancesUpdateRequestFieldAmount)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AllowancesUpdateRequest) SetDescription(description *string) {
	a.Description = description
	a.require(allowancesUpdateRequestFieldDescription)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AllowancesUpdateRequest) SetExpiresAt(expiresAt *time.Time) {
	a.ExpiresAt = expiresAt
	a.require(allowancesUpdateRequestFieldExpiresAt)
}

func (a *AllowancesUpdateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AllowancesUpdateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AllowancesUpdateRequest(body)
	return nil
}

func (a *AllowancesUpdateRequest) MarshalJSON() ([]byte, error) {
	type embed AllowancesUpdateRequest
	var marshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expires_at,omitempty"`
	}{
		embed:     embed(*a),
		ExpiresAt: internal.NewOptionalDateTime(a.ExpiresAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}
