// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	os "os"

	basistheory "github.com/Basis-Theory/go-sdk/v5"
	core "github.com/Basis-Theory/go-sdk/v5/core"
	internal "github.com/Basis-Theory/go-sdk/v5/internal"
	option "github.com/Basis-Theory/go-sdk/v5/option"
	connections "github.com/Basis-Theory/go-sdk/v5/tenants/connections"
	invitations "github.com/Basis-Theory/go-sdk/v5/tenants/invitations"
	members "github.com/Basis-Theory/go-sdk/v5/tenants/members"
	merchants "github.com/Basis-Theory/go-sdk/v5/tenants/merchants"
	owner "github.com/Basis-Theory/go-sdk/v5/tenants/owner"
	securitycontact "github.com/Basis-Theory/go-sdk/v5/tenants/securitycontact"
	self "github.com/Basis-Theory/go-sdk/v5/tenants/self"
)

type Client struct {
	WithRawResponse *RawClient
	SecurityContact *securitycontact.Client
	Connections     *connections.Client
	Invitations     *invitations.Client
	Members         *members.Client
	Merchants       *merchants.Client
	Owner           *owner.Client
	Self            *self.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		SecurityContact: securitycontact.NewClient(options),
		Connections:     connections.NewClient(options),
		Invitations:     invitations.NewClient(options),
		Members:         members.NewClient(options),
		Merchants:       merchants.NewClient(options),
		Owner:           owner.NewClient(options),
		Self:            self.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) OwnerTransfer(
	ctx context.Context,
	request *basistheory.TransferTenantOwnerRequest,
	opts ...option.RequestOption,
) (*basistheory.TenantMemberResponse, error) {
	response, err := c.WithRawResponse.OwnerTransfer(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
