// Code generated by Fern. DO NOT EDIT.

package connection

import (
	v2 "github.com/Basis-Theory/go-sdk/v2"
)

type ApplePayTokenizeRequest struct {
	ApplePaymentMethodToken *v2.ApplePayMethodToken `json:"apple_payment_method_token,omitempty" url:"-"`
}
