// Code generated by Fern. DO NOT EDIT.

package connection

import (
	v3 "github.com/Basis-Theory/go-sdk/v3"
)

type ApplePayTokenizeRequest struct {
	ApplePaymentMethodToken *v3.ApplePayMethodToken `json:"apple_payment_method_token,omitempty" url:"-"`
}
