// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	os "os"

	basistheory "github.com/Basis-Theory/go-sdk/v5"
	core "github.com/Basis-Theory/go-sdk/v5/core"
	googlepay "github.com/Basis-Theory/go-sdk/v5/googlepay"
	certificates "github.com/Basis-Theory/go-sdk/v5/googlepay/merchant/certificates"
	internal "github.com/Basis-Theory/go-sdk/v5/internal"
	option "github.com/Basis-Theory/go-sdk/v5/option"
)

type Client struct {
	WithRawResponse *RawClient
	Certificates    *certificates.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		Certificates:    certificates.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) Get(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*basistheory.GooglePayMerchant, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) Create(
	ctx context.Context,
	request *googlepay.GooglePayMerchantRegisterRequest,
	opts ...option.RequestOption,
) (*basistheory.GooglePayMerchant, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
