// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	v5 "github.com/Basis-Theory/go-sdk/v5"
	core "github.com/Basis-Theory/go-sdk/v5/core"
	client "github.com/Basis-Theory/go-sdk/v5/googlepay/merchant/client"
	internal "github.com/Basis-Theory/go-sdk/v5/internal"
	option "github.com/Basis-Theory/go-sdk/v5/option"
	http "net/http"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient
	Merchant        *client.Client

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		Merchant:        client.NewClient(opts...),
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

func (c *Client) Create(
	ctx context.Context,
	request *v5.GooglePayCreateRequest,
	opts ...option.RequestOption,
) (*v5.GooglePayCreateResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*v5.GooglePayToken, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}
