// Code generated by Fern. DO NOT EDIT.

package sessions

import (
	context "context"
	v2 "github.com/Basis-Theory/go-sdk/v2"
	core "github.com/Basis-Theory/go-sdk/v2/core"
	internal "github.com/Basis-Theory/go-sdk/v2/internal"
	option "github.com/Basis-Theory/go-sdk/v2/option"
	threeds "github.com/Basis-Theory/go-sdk/v2/threeds"
	http "net/http"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

func (c *Client) Create(
	ctx context.Context,
	request *threeds.CreateThreeDsSessionRequest,
	opts ...option.RequestOption,
) (*v2.CreateThreeDsSessionResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Authenticate(
	ctx context.Context,
	sessionID string,
	request *v2.AuthenticateThreeDsSessionRequest,
	opts ...option.IdempotentRequestOption,
) (*v2.ThreeDsAuthentication, error) {
	response, err := c.WithRawResponse.Authenticate(
		ctx,
		sessionID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetChallengeResult(
	ctx context.Context,
	sessionID string,
	opts ...option.RequestOption,
) (*v2.ThreeDsAuthentication, error) {
	response, err := c.WithRawResponse.GetChallengeResult(
		ctx,
		sessionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*v2.ThreeDsSession, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
