// Code generated by Fern. DO NOT EDIT.

package jobs

import (
	context "context"
	v5 "github.com/Basis-Theory/go-sdk/v5"
	accountupdater "github.com/Basis-Theory/go-sdk/v5/accountupdater"
	core "github.com/Basis-Theory/go-sdk/v5/core"
	internal "github.com/Basis-Theory/go-sdk/v5/internal"
	option "github.com/Basis-Theory/go-sdk/v5/option"
	http "net/http"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Returns the account updater batch job
func (c *Client) Get(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*v5.AccountUpdaterJob, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a list of account updater batch jobs
func (c *Client) List(
	ctx context.Context,
	request *accountupdater.JobsListRequest,
	opts ...option.RequestOption,
) (*v5.AccountUpdaterJobList, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the created account updater batch job
func (c *Client) Create(
	ctx context.Context,
	opts ...option.RequestOption,
) (*v5.AccountUpdaterJob, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
