// Code generated by Fern. DO NOT EDIT.

package members

import (
	context "context"
	fmt "fmt"
	http "net/http"
	os "os"
	strconv "strconv"

	basistheory "github.com/Basis-Theory/go-sdk/v6"
	core "github.com/Basis-Theory/go-sdk/v6/core"
	internal "github.com/Basis-Theory/go-sdk/v6/internal"
	option "github.com/Basis-Theory/go-sdk/v6/option"
	tenants "github.com/Basis-Theory/go-sdk/v6/tenants"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) List(
	ctx context.Context,
	request *tenants.MembersListRequest,
	opts ...option.RequestOption,
) (*core.Page[*int, *basistheory.TenantMemberResponse, *basistheory.TenantMemberResponsePaginatedList], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.basistheory.com",
	)
	endpointURL := baseURL + "/tenants/self/members"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	headers := internal.MergeHeaders(
		c.options.ToHeader(),
		options.ToHeader(),
	)
	prepareCall := func(pageRequest *core.PageRequest[*int]) *internal.CallParams {
		if pageRequest.Cursor != nil {
			queryParams.Set("page", fmt.Sprintf("%v", *pageRequest.Cursor))
		}
		nextURL := endpointURL
		if len(queryParams) > 0 {
			nextURL += "?" + queryParams.Encode()
		}
		return &internal.CallParams{
			URL:             nextURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        pageRequest.Response,
			ErrorDecoder:    internal.NewErrorDecoder(basistheory.ErrorCodes),
		}
	}
	next := 1
	if queryParams.Has("page") {
		var err error
		if next, err = strconv.Atoi(queryParams.Get("page")); err != nil {
			return nil, err
		}
	}

	readPageResponse := func(response *basistheory.TenantMemberResponsePaginatedList) *core.PageResponse[*int, *basistheory.TenantMemberResponse, *basistheory.TenantMemberResponsePaginatedList] {
		next += 1
		results := response.GetData()
		return &core.PageResponse[*int, *basistheory.TenantMemberResponse, *basistheory.TenantMemberResponsePaginatedList]{
			Results:  results,
			Response: response,
			Next:     &next,
		}
	}
	pager := internal.NewOffsetPager(
		c.caller,
		prepareCall,
		readPageResponse,
	)
	return pager.GetPage(ctx, &next)
}

func (c *Client) Update(
	ctx context.Context,
	memberID string,
	request *tenants.UpdateTenantMemberRequest,
	opts ...option.IdempotentRequestOption,
) (*basistheory.TenantMemberResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		memberID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	memberID string,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		memberID,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
