// Code generated by Fern. DO NOT EDIT.

package accountupdater

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreateAccountUpdaterJobRequest(t *testing.T) {
	t.Run("SetDeduplicateTokens", func(t *testing.T) {
		obj := &CreateAccountUpdaterJobRequest{}
		var fernTestValueDeduplicateTokens *bool
		obj.SetDeduplicateTokens(fernTestValueDeduplicateTokens)
		assert.Equal(t, fernTestValueDeduplicateTokens, obj.DeduplicateTokens)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMerchantID", func(t *testing.T) {
		obj := &CreateAccountUpdaterJobRequest{}
		var fernTestValueMerchantID *string
		obj.SetMerchantID(fernTestValueMerchantID)
		assert.Equal(t, fernTestValueMerchantID, obj.MerchantID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResultVersion", func(t *testing.T) {
		obj := &CreateAccountUpdaterJobRequest{}
		var fernTestValueResultVersion *CreateAccountUpdaterJobRequestResultVersion
		obj.SetResultVersion(fernTestValueResultVersion)
		assert.Equal(t, fernTestValueResultVersion, obj.ResultVersion)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateAccountUpdaterJobRequest(t *testing.T) {
	t.Run("SetDeduplicateTokens_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAccountUpdaterJobRequest{}
		var fernTestValueDeduplicateTokens *bool

		// Act
		obj.SetDeduplicateTokens(fernTestValueDeduplicateTokens)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMerchantID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAccountUpdaterJobRequest{}
		var fernTestValueMerchantID *string

		// Act
		obj.SetMerchantID(fernTestValueMerchantID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResultVersion_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateAccountUpdaterJobRequest{}
		var fernTestValueResultVersion *CreateAccountUpdaterJobRequestResultVersion

		// Act
		obj.SetResultVersion(fernTestValueResultVersion)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersJobsListRequest(t *testing.T) {
	t.Run("SetSize", func(t *testing.T) {
		obj := &JobsListRequest{}
		var fernTestValueSize *int
		obj.SetSize(fernTestValueSize)
		assert.Equal(t, fernTestValueSize, obj.Size)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStart", func(t *testing.T) {
		obj := &JobsListRequest{}
		var fernTestValueStart *string
		obj.SetStart(fernTestValueStart)
		assert.Equal(t, fernTestValueStart, obj.Start)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitJobsListRequest(t *testing.T) {
	t.Run("SetSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &JobsListRequest{}
		var fernTestValueSize *int

		// Act
		obj.SetSize(fernTestValueSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStart_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &JobsListRequest{}
		var fernTestValueStart *string

		// Act
		obj.SetStart(fernTestValueStart)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumCreateAccountUpdaterJobRequestResultVersion(t *testing.T) {
	t.Run("NewFromString_1", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateAccountUpdaterJobRequestResultVersionFromString("1")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateAccountUpdaterJobRequestResultVersion("1"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_1_1", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateAccountUpdaterJobRequestResultVersionFromString("1.1")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateAccountUpdaterJobRequestResultVersion("1.1"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_1_2", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateAccountUpdaterJobRequestResultVersionFromString("1.2")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateAccountUpdaterJobRequestResultVersion("1.2"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreateAccountUpdaterJobRequestResultVersionFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreateAccountUpdaterJobRequestResultVersionFromString("1")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
