// Code generated by Fern. DO NOT EDIT.

package tenants

import (
	basistheory "github.com/Basis-Theory/go-sdk/v5"
	core "github.com/Basis-Theory/go-sdk/v5/core"
	internal "github.com/Basis-Theory/go-sdk/v5/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	401: func(apiError *core.APIError) error {
		return &basistheory.UnauthorizedError{
			APIError: apiError,
		}
	},
	403: func(apiError *core.APIError) error {
		return &basistheory.ForbiddenError{
			APIError: apiError,
		}
	},
	503: func(apiError *core.APIError) error {
		return &basistheory.ServiceUnavailableError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &basistheory.BadRequestError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &basistheory.NotFoundError{
			APIError: apiError,
		}
	},
	422: func(apiError *core.APIError) error {
		return &basistheory.UnprocessableEntityError{
			APIError: apiError,
		}
	},
	409: func(apiError *core.APIError) error {
		return &basistheory.ConflictError{
			APIError: apiError,
		}
	},
}
