// This file was auto-generated by Fern from our API Definition.

package tenants

import (
	v2 "github.com/Basis-Theory/go-sdk/v2"
)

type CreateTenantInvitationRequest struct {
	Email string  `json:"email" url:"-"`
	Role  *string `json:"role,omitempty" url:"-"`
}

type InvitationsListRequest struct {
	Status *v2.TenantInvitationStatus `json:"-" url:"status,omitempty"`
	Page   *int                       `json:"-" url:"page,omitempty"`
	Start  *string                    `json:"-" url:"start,omitempty"`
	Size   *int                       `json:"-" url:"size,omitempty"`
}
