// Code generated by Fern. DO NOT EDIT.

package connections

import (
	context "context"
	os "os"

	basistheory "github.com/Basis-Theory/go-sdk/v6"
	core "github.com/Basis-Theory/go-sdk/v6/core"
	internal "github.com/Basis-Theory/go-sdk/v6/internal"
	option "github.com/Basis-Theory/go-sdk/v6/option"
	tenants "github.com/Basis-Theory/go-sdk/v6/tenants"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("BT-API-KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) Create(
	ctx context.Context,
	request *tenants.CreateTenantConnectionRequest,
	opts ...option.IdempotentRequestOption,
) (*basistheory.CreateTenantConnectionResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Delete(
	ctx context.Context,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
