// Code generated by Fern. DO NOT EDIT.

package rails

import (
	context "context"
	http "net/http"

	basistheory "github.com/Basis-Theory/go-sdk/v7"
	paymentmethods "github.com/Basis-Theory/go-sdk/v7/agentic/paymentmethods"
	core "github.com/Basis-Theory/go-sdk/v7/core"
	internal "github.com/Basis-Theory/go-sdk/v7/internal"
	option "github.com/Basis-Theory/go-sdk/v7/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Retry(
	ctx context.Context,
	paymentMethodID string,
	request *paymentmethods.RailsRetryRequest,
	opts ...option.RequestOption,
) (*core.Response[*basistheory.PaymentMethod], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.basistheory.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agentic/payment-methods/%v/rails/retry",
		paymentMethodID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *basistheory.PaymentMethod
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(paymentmethods.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*basistheory.PaymentMethod]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
