name: ci

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4

      - name: Compile
        run: go build ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4

      - name: Test
        run: go test ./...
        env:
          BT_API_URL: https://api.flock-dev.com
          BT_MGT_API_KEY: ${{ secrets.BT_SDK_INT_TEST_MGT_API_KEY }}
          BT_PVT_API_KEY: ${{ secrets.BT_SDK_INT_TEST_PVT_API_KEY }}
