name: ci

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: PR
    name: Build
    strategy:
      matrix:
        go-version: [ '1.22', '1.23' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Compile
        run: go build ./...

      - name: Test
        run: go test ./...
        env:
          BT_API_URL: https://api.flock-dev.com
          BT_MGT_API_KEY: ${{ secrets.BT_SDK_INT_TEST_MGT_API_KEY }}
          BT_PVT_API_KEY: ${{ secrets.BT_SDK_INT_TEST_PVT_API_KEY }}

    pr-security-check:
      name: PR Security Check
      uses: Basis-Theory/security-workflows/.github/workflows/pr-check.yml@master
      secrets: inherit